---
name: Deploy Roja App
description: Template for deploying a Node.js app
categories: [deployment]
---

name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Deploying app..."
